import { ROLES } from './constants.js';

export const PERMISSIONS = {
  USERS_VIEW_ALL: 'users:view_all',
  USERS_CREATE: 'users:create',
  USERS_EDIT: 'users:edit',
  USERS_DELETE: 'users:delete',
  USERS_RESET_PASSWORD: 'users:reset_password',

  MEMBERS_VIEW_ALL: 'members:view_all',
  MEMBERS_VIEW_ZONE: 'members:view_zone',
  MEMBERS_CREATE: 'members:create',
  MEMBERS_EDIT: 'members:edit',
  MEMBERS_DELETE: 'members:delete',
  MEMBERS_BULK_IMPORT: 'members:bulk_import',
  MEMBERS_VIEW_TIMELINE: 'members:view_timeline',
  MEMBERS_MESSAGE: 'members:message',

  EVENTS_VIEW_ALL: 'events:view_all',
  EVENTS_VIEW_ZONE: 'events:view_zone',
  EVENTS_CREATE: 'events:create',
  EVENTS_EDIT_OWN: 'events:edit_own',
  EVENTS_EDIT_ALL: 'events:edit_all',
  EVENTS_DELETE: 'events:delete',

  PROGRAMS_MANAGE: 'programs:manage',

  DASHBOARD_VIEW_ALL: 'dashboard:view_all',
  DASHBOARD_VIEW_ZONE: 'dashboard:view_zone',

  FEEDBACK_VIEW_ALL: 'feedback:view_all',
  FEEDBACK_VIEW_ZONE: 'feedback:view_zone',

  REPORTS_EXPORT: 'reports:export',
  BACKUP_VIEW: 'backup:view',

  ATTENDANCE_VIEW: 'attendance:view',
  ATTENDANCE_CREATE: 'attendance:create',
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  
  [ROLES.COMMUNITY_MANAGER]: [
    PERMISSIONS.MEMBERS_VIEW_ALL,
    PERMISSIONS.MEMBERS_CREATE,
    PERMISSIONS.MEMBERS_EDIT,
    PERMISSIONS.MEMBERS_BULK_IMPORT,
    PERMISSIONS.MEMBERS_VIEW_TIMELINE,
    PERMISSIONS.MEMBERS_MESSAGE,
    PERMISSIONS.EVENTS_VIEW_ALL,
    PERMISSIONS.EVENTS_CREATE,
    PERMISSIONS.EVENTS_EDIT_ALL,
    PERMISSIONS.EVENTS_DELETE,
    PERMISSIONS.PROGRAMS_MANAGE,
    PERMISSIONS.DASHBOARD_VIEW_ALL,
    PERMISSIONS.FEEDBACK_VIEW_ALL,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
  ],
  
  [ROLES.CASE_MANAGER]: [
    PERMISSIONS.MEMBERS_VIEW_ZONE,
    PERMISSIONS.MEMBERS_CREATE,
    PERMISSIONS.MEMBERS_EDIT,
    PERMISSIONS.MEMBERS_VIEW_TIMELINE,
    PERMISSIONS.MEMBERS_MESSAGE,
    PERMISSIONS.EVENTS_VIEW_ZONE,
    PERMISSIONS.EVENTS_CREATE,
    PERMISSIONS.EVENTS_EDIT_OWN,
    PERMISSIONS.DASHBOARD_VIEW_ZONE,
    PERMISSIONS.FEEDBACK_VIEW_ZONE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
  ],
  
  [ROLES.AREA_MANAGER]: [
    PERMISSIONS.MEMBERS_VIEW_ZONE,
    PERMISSIONS.EVENTS_VIEW_ZONE,
    PERMISSIONS.DASHBOARD_VIEW_ZONE,
    PERMISSIONS.FEEDBACK_VIEW_ZONE,
    PERMISSIONS.ATTENDANCE_VIEW,
  ],
  
  [ROLES.MENTOR]: [
    PERMISSIONS.MEMBERS_VIEW_ZONE,
    PERMISSIONS.MEMBERS_VIEW_TIMELINE,
    PERMISSIONS.EVENTS_VIEW_ZONE,
    PERMISSIONS.EVENTS_CREATE,
    PERMISSIONS.DASHBOARD_VIEW_ZONE,
    PERMISSIONS.FEEDBACK_VIEW_ZONE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
  ],
  
  [ROLES.MENTEE]: [
    PERMISSIONS.EVENTS_VIEW_ZONE,
    PERMISSIONS.DASHBOARD_VIEW_ZONE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
  ],
  
  [ROLES.YOUTH_ENGAGEMENT_LEADER]: [
    PERMISSIONS.MEMBERS_VIEW_ZONE,
    PERMISSIONS.MEMBERS_CREATE,
    PERMISSIONS.MEMBERS_EDIT,
    PERMISSIONS.MEMBERS_VIEW_TIMELINE,
    PERMISSIONS.EVENTS_VIEW_ZONE,
    PERMISSIONS.EVENTS_CREATE,
    PERMISSIONS.EVENTS_EDIT_OWN,
    PERMISSIONS.DASHBOARD_VIEW_ZONE,
    PERMISSIONS.FEEDBACK_VIEW_ZONE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
  ],
  
  [ROLES.COMMUNITY_ENGAGEMENT_LEADER]: [
    PERMISSIONS.MEMBERS_VIEW_ZONE,
    PERMISSIONS.MEMBERS_CREATE,
    PERMISSIONS.MEMBERS_EDIT,
    PERMISSIONS.MEMBERS_VIEW_TIMELINE,
    PERMISSIONS.MEMBERS_MESSAGE,
    PERMISSIONS.EVENTS_VIEW_ZONE,
    PERMISSIONS.EVENTS_CREATE,
    PERMISSIONS.EVENTS_EDIT_OWN,
    PERMISSIONS.DASHBOARD_VIEW_ZONE,
    PERMISSIONS.FEEDBACK_VIEW_ZONE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
  ],
  
  [ROLES.COMMUNITY_ENGAGEMENT_ASSOCIATE]: [
    PERMISSIONS.MEMBERS_VIEW_ZONE,
    PERMISSIONS.EVENTS_VIEW_ZONE,
    PERMISSIONS.DASHBOARD_VIEW_ZONE,
    PERMISSIONS.FEEDBACK_VIEW_ZONE,
    PERMISSIONS.ATTENDANCE_VIEW,
  ],
  
  [ROLES.ASSISTANT_PROJECT_ASSOCIATE]: [
    PERMISSIONS.MEMBERS_VIEW_ZONE,
    PERMISSIONS.MEMBERS_CREATE,
    PERMISSIONS.MEMBERS_EDIT,
    PERMISSIONS.MEMBERS_VIEW_TIMELINE,
    PERMISSIONS.EVENTS_VIEW_ZONE,
    PERMISSIONS.EVENTS_CREATE,
    PERMISSIONS.DASHBOARD_VIEW_ZONE,
    PERMISSIONS.FEEDBACK_VIEW_ZONE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
  ],
  
  [ROLES.OTHER]: [
    PERMISSIONS.MEMBERS_VIEW_ZONE,
    PERMISSIONS.EVENTS_VIEW_ZONE,
    PERMISSIONS.DASHBOARD_VIEW_ZONE,
    PERMISSIONS.ATTENDANCE_VIEW,
  ],
};

export const SELF_SIGNUP_ROLES = [ROLES.CASE_MANAGER, ROLES.AREA_MANAGER, ROLES.MENTOR, ROLES.MENTEE, ROLES.YOUTH_ENGAGEMENT_LEADER, ROLES.COMMUNITY_ENGAGEMENT_LEADER, ROLES.COMMUNITY_ENGAGEMENT_ASSOCIATE, ROLES.ASSISTANT_PROJECT_ASSOCIATE, ROLES.OTHER];

export const getPermissionsForRole = (role) => {
  return ROLE_PERMISSIONS[role] || [];
};

export const hasPermission = (role, permission) => {
  const permissions = getPermissionsForRole(role);
  return permissions.includes(permission);
};
